# Set theme
remote_theme: daviddarnes/alembic
theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://pull-fiction.github.io/make-crops-not-war/'
baseurl: 'https://pull-fiction.github.io/make-crops-not-war/'
title: 'Make Crops, not War!'
description: 'ADA 2019 Project data story'
permalink: pretty
# logo: ""

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Make Crops, not War!
  url: /

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "assets/img/holiday-inn.jpg"
