# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://pull-fiction.github.io'
baseurl: '/make-crops-not-war'
title: 'Make Crops, not War!'
description: 'An ADA 2019 data story'
permalink: pretty
markdown: kramdown
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
